dist: trusty
language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpcs --standard=psr2 src/ --ignore=migrations/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false
