language: php

php:
  - 5.6
  - 7.1

sudo: false

addons:
    code_climate:
        repo_token: 441de3889b72f808210dc970c4bc95836c6f5f5145c9bafc338afdd2d0e0a5ae

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter

matrix:
  allow_failures:
    - php: 5.6
